import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { CHAPTERS } from './validate-content.mjs';

const texts = new Set(CHAPTERS.flatMap(chapter => chapter.vocabulary.flatMap(category =>
  category.entries.map(entry => [entry.article, entry.term.replace(/\|/g, '')].filter(Boolean).join(' ').trim()),
)));
texts.add('Guten Tag! Ich lerne Deutsch. Übung macht den Meister.');
const manifest = Object.fromEntries([...texts].sort().map(text => [text,
  `audio/de/${createHash('sha256').update(text).digest('hex').slice(0, 16)}.mp3`,
]));
mkdirSync(new URL('../public/audio/de/', import.meta.url), { recursive: true });
writeFileSync(new URL('../public/audio/de/manifest.json', import.meta.url), JSON.stringify(manifest, null, 2) + '\n');
writeFileSync(new URL('../src/app/data/pronunciation-audio.ts', import.meta.url),
  '// Generated by scripts/export-audio.mjs. German Katja neural voice.\nexport const PRONUNCIATION_AUDIO: Readonly<Record<string, string>> = ' + JSON.stringify(manifest, null, 2) + ';\n');
console.log(`Exported ${texts.size} German pronunciations.`);
